=== jzsalinas/galaxy-morphology-discovery/oc3/schemas/oc3_psf_identities_001.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "OC3 frozen PSF observational identities 001",
  "type": "object",
  "additionalProperties": false,
  "required": ["schema_version", "stage_id", "locations_binding", "base_contract", "counts", "identities", "sealed"],
  "properties": {
    "schema_version": {"const": "OC3_PSF_IDENTITIES_001"},
    "stage_id": {"const": "OC3-COADD-PSF-CONTRACT-PROBE-001"},
    "locations_binding": {"type": "object"},
    "base_contract": {"type": "object"},
    "counts": {"type": "object"},
    "identities": {
      "type": "array",
      "minItems": 54,
      "maxItems": 54,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["identity_id", "slot", "region", "brick", "point_id", "native_x", "native_y", "ra", "dec", "band", "transport_id"],
        "properties": {
          "identity_id": {"type": "string"},
          "slot": {"enum": ["S1", "S2", "S3", "N1", "N2", "N3"]},
          "region": {"enum": ["south", "north"]},
          "brick": {"type": "string"},
          "point_id": {"enum": ["P0", "P1", "P2"]},
          "native_x": {"type": "number"},
          "native_y": {"type": "number"},
          "ra": {"type": "number"},
          "dec": {"type": "number"},
          "band": {"enum": ["g", "r", "z"]},
          "transport_id": {"type": "string"}
        }
      }
    },
    "sealed": {"type": "string", "pattern": "^[0-9a-f]{64}$"}
  }
}

=== jzsalinas/galaxy-morphology-discovery/oc3/TECHNICAL_INDEX/OC3_PSF_IDENTITIES.json
{"base_contract":{"path":"oc3/INPUTS/OC3_PSF_RESOURCE_CONTRACT_001.json","sha256":"1720e8ae9b77f4d5b7de9b7d28a2dbf3d1785c7005e2507e9a9ba21467dbc9f7"},"counts":{"locations":6,"observational_identities":54,"spatial_points":18},"identities":[{"band":"g","brick":"3443m052","dec":-5.287807632301723,"identity_id":"oc3psf_27e40bf2a588bbad8ec87ffa","native_x":2112,"native_y":1280,"point_id":"P0","ra":344.3086360731805,"region":"south","slot":"S1","transport_id":"oc3psft_bd60b870a038e32de6b11237"},{"band":"r","brick":"3443m052","dec":-5.287807632301723,"identity_id":"oc3psf_a9f7b52763efe81db14a82be","native_x":2112,"native_y":1280,"point_id":"P0","ra":344.3086360731805,"region":"south","slot":"S1","transport_id":"oc3psft_bd60b870a038e32de6b11237"},{"band":"z","brick":"3443m052","dec":-5.287807632301723,"identity_id":"oc3psf_5467dd2f2796e835953320c1","native_x":2112,"native_y":1280,"point_id":"P0","ra":344.3086360731805,"region":"south","slot":"S1","transport_id":"oc3psft_bd60b870a038e32de6b11237"},{"band":"g","brick":"3443m052","dec":-5.290136601141627,"identity_id":"oc3psf_0a70d20bc789e2b7f237e524","native_x":2080,"native_y":1248,"point_id":"P1","ra":344.3109748379873,"region":"south","slot":"S1","transport_id":"oc3psft_77d6d7ebc83d1b0bf935f6c3"},{"band":"r","brick":"3443m052","dec":-5.290136601141627,"identity_id":"oc3psf_9857c3169a30d11b0b75dae0","native_x":2080,"native_y":1248,"point_id":"P1","ra":344.3109748379873,"region":"south","slot":"S1","transport_id":"oc3psft_77d6d7ebc83d1b0bf935f6c3"},{"band":"z","brick":"3443m052","dec":-5.290136601141627,"identity_id":"oc3psf_cb898741ec65cc569f72e360","native_x":2080,"native_y":1248,"point_id":"P1","ra":344.3109748379873,"region":"south","slot":"S1","transport_id":"oc3psft_77d6d7ebc83d1b0bf935f6c3"},{"band":"g","brick":"3443m052","dec":-5.285478654651484,"identity_id":"oc3psf_f37359e79a14031f19917afd","native_x":2144,"native_y":1312,"point_id":"P2","ra":344.3062973259209,"region":"south","slot":"S1","transport_id":"oc3psft_448a145bcc7c38059565f36f"},{"band":"r","brick":"3443m052","dec":-5.285478654651484,"identity_id":"oc3psf_c1f2027055ccb47e3b9d0734","native_x":2144,"native_y":1312,"point_id":"P2","ra":344.3062973259209,"region":"south","slot":"S1","transport_id":"oc3psft_448a145bcc7c38059565f36f"},{"band":"z","brick":"3443m052","dec":-5.285478654651484,"identity_id":"oc3psf_69b823dc0a459238cae6b2d7","native_x":2144,"native_y":1312,"point_id":"P2","ra":344.3062973259209,"region":"south","slot":"S1","transport_id":"oc3psft_448a145bcc7c38059565f36f"},{"band":"g","brick":"3443m052","dec":-5.124785588062867,"identity_id":"oc3psf_a5c4b702d20fe5b2c395f0c9","native_x":1472,"native_y":3520,"point_id":"P0","ra":344.3554066481134,"region":"south","slot":"S2","transport_id":"oc3psft_0eeeb554e0bfb9849ddccfba"},{"band":"r","brick":"3443m052","dec":-5.124785588062867,"identity_id":"oc3psf_0fc9a6493cb208d7b4e5f019","native_x":1472,"native_y":3520,"point_id":"P0","ra":344.3554066481134,"region":"south","slot":"S2","transport_id":"oc3psft_0eeeb554e0bfb9849ddccfba"},{"band":"z","brick":"3443m052","dec":-5.124785588062867,"identity_id":"oc3psf_4b1394d58c0a6be5ed355500","native_x":1472,"native_y":3520,"point_id":"P0","ra":344.3554066481134,"region":"south","slot":"S2","transport_id":"oc3psft_0eeeb554e0bfb9849ddccfba"},{"band":"g","brick":"3443m052","dec":-5.1271143746595005,"identity_id":"oc3psf_3fff5c844b3b8ec26dbb9a6c","native_x":1440,"native_y":3488,"point_id":"P1","ra":344.35774497612016,"region":"south","slot":"S2","transport_id":"oc3psft_280db063f1865daf79666e2c"},{"band":"r","brick":"3443m052","dec":-5.1271143746595005,"identity_id":"oc3psf_5ec002f4f2b0006754acbbc0","native_x":1440,"native_y":3488,"point_id":"P1","ra":344.35774497612016,"region":"south","slot":"S2","transport_id":"oc3psft_280db063f1865daf79666e2c"},{"band":"z","brick":"3443m052","dec":-5.1271143746595005,"identity_id":"oc3psf_029b4eb87650fecf3138ded7","native_x":1440,"native_y":3488,"point_id":"P1","ra":344.35774497612016,"region":"south","slot":"S2","transport_id":"oc3psft_280db063f1865daf79666e2c"},{"band":"g","brick":"3443m052","dec":-5.122456793310956,"identity_id":"oc3psf_50da44320b2eaad2a1eb53a5","native_x":1504,"native_y":3552,"point_id":"P2","ra":344.3530683374903,"region":"south","slot":"S2","transport_id":"oc3psft_fe4f2fb83aabe156ea956931"},{"band":"r","brick":"3443m052","dec":-5.122456793310956,"identity_id":"oc3psf_b7098589196ec12701a66555","native_x":1504,"native_y":3552,"point_id":"P2","ra":344.3530683374903,"region":"south","slot":"S2","transport_id":"oc3psft_fe4f2fb83aabe156ea956931"},{"band":"z","brick":"3443m052","dec":-5.122456793310956,"identity_id":"oc3psf_6b95dbe2903251da5472d2d6","native_x":1504,"native_y":3552,"point_id":"P2","ra":344.3530683374903,"region":"south","slot":"S2","transport_id":"oc3psft_fe4f2fb83aabe156ea956931"},{"band":"g","brick":"3443m052","dec":-5.138756376986385,"identity_id":"oc3psf_b285da5aa4d9724eb7b12165","native_x":960,"native_y":3328,"point_id":"P0","ra":344.39281968629297,"region":"south","slot":"S3","transport_id":"oc3psft_0c8ff7a704d65fc12ea3f718"},{"band":"r","brick":"3443m052","dec":-5.138756376986385,"identity_id":"oc3psf_d20f07b480658c48a210527f","native_x":960,"native_y":3328,"point_id":"P0","ra":344.39281968629297,"region":"south","slot":"S3","transport_id":"oc3psft_0c8ff7a704d65fc12ea3f718"},{"band":"z","brick":"3443m052","dec":-5.138756376986385,"identity_id":"oc3psf_fb79c1feeb3b7d46d9c74817","native_x":960,"native_y":3328,"point_id":"P0","ra":344.39281968629297,"region":"south","slot":"S3","transport_id":"oc3psft_0c8ff7a704d65fc12ea3f718"},{"band":"g","brick":"3443m052","dec":-5.141085028254463,"identity_id":"oc3psf_b52d355af2353361b9310a65","native_x":928,"native_y":3296,"point_id":"P1","ra":344.39515820406643,"region":"south","slot":"S3","transport_id":"oc3psft_e31fb6477252802c4659d12e"},{"band":"r","brick":"3443m052","dec":-5.141085028254463,"identity_id":"oc3psf_dc39a1273b6573c90653069c","native_x":928,"native_y":3296,"point_id":"P1","ra":344.39515820406643,"region":"south","slot":"S3","transport_id":"oc3psft_e31fb6477252802c4659d12e"},{"band":"z","brick":"3443m052","dec":-5.141085028254463,"identity_id":"oc3psf_504ec18a213aa5a1809bc337","native_x":928,"native_y":3296,"point_id":"P1","ra":344.39515820406643,"region":"south","slot":"S3","transport_id":"oc3psft_e31fb6477252802c4659d12e"},{"band":"g","brick":"3443m052","dec":-5.136427717369462,"identity_id":"oc3psf_f8a2b273f1953e54734f4efb","native_x":992,"native_y":3360,"point_id":"P2","ra":344.3904811857803,"region":"south","slot":"S3","transport_id":"oc3psft_3393dcb252257b97ae0051c0"},{"band":"r","brick":"3443m052","dec":-5.136427717369462,"identity_id":"oc3psf_d36fb0004e9e77882c0a66de","native_x":992,"native_y":3360,"point_id":"P2","ra":344.3904811857803,"region":"south","slot":"S3","transport_id":"oc3psft_3393dcb252257b97ae0051c0"},{"band":"z","brick":"3443m052","dec":-5.136427717369462,"identity_id":"oc3psf_ee794b6f1a603464225358a9","native_x":992,"native_y":3360,"point_id":"P2","ra":344.3904811857803,"region":"south","slot":"S3","transport_id":"oc3psft_3393dcb252257b97ae0051c0"},{"band":"g","brick":"2478p325","dec":32.550669652255074,"identity_id":"oc3psf_9aeb7caef4ecac34c0fa2964","native_x":2624,"native_y":2496,"point_id":"P0","ra":247.76132462859286,"region":"north","slot":"N1","transport_id":"oc3psft_ea9facb3e4d9f7bf83675506"},{"band":"r","brick":"2478p325","dec":32.550669652255074,"identity_id":"oc3psf_2cc3bdba7010f11d003ab90b","native_x":2624,"native_y":2496,"point_id":"P0","ra":247.76132462859286,"region":"north","slot":"N1","transport_id":"oc3psft_ea9facb3e4d9f7bf83675506"},{"band":"z","brick":"2478p325","dec":32.550669652255074,"identity_id":"oc3psf_0b0b1a69a6b000cc45a9fa6a","native_x":2624,"native_y":2496,"point_id":"P0","ra":247.76132462859286,"region":"north","slot":"N1","transport_id":"oc3psft_ea9facb3e4d9f7bf83675506"},{"band":"g","brick":"2478p325","dec":32.548342293413164,"identity_id":"oc3psf_99728363622508445fac5ddd","native_x":2592,"native_y":2464,"point_id":"P1","ra":247.76408929255774,"region":"north","slot":"N1","transport_id":"oc3psft_8fa7df0e9b7ea2cc1be82b0d"},{"band":"r","brick":"2478p325","dec":32.548342293413164,"identity_id":"oc3psf_65586aa089ee4e1fda572c38","native_x":2592,"native_y":2464,"point_id":"P1","ra":247.76408929255774,"region":"north","slot":"N1","transport_id":"oc3psft_8fa7df0e9b7ea2cc1be82b0d"},{"band":"z","brick":"2478p325","dec":32.548342293413164,"identity_id":"oc3psf_59cc0239f54dae64d349b7a7","native_x":2592,"native_y":2464,"point_id":"P1","ra":247.76408929255774,"region":"north","slot":"N1","transport_id":"oc3psft_8fa7df0e9b7ea2cc1be82b0d"},{"band":"g","brick":"2478p325","dec":32.552996950226984,"identity_id":"oc3psf_80a066504748f9d9455f2009","native_x":2656,"native_y":2528,"point_id":"P2","ra":247.75855982169392,"region":"north","slot":"N1","transport_id":"oc3psft_b9e316799740d2d24bc26dd1"},{"band":"r","brick":"2478p325","dec":32.552996950226984,"identity_id":"oc3psf_8335b1a17e71bf75847044d3","native_x":2656,"native_y":2528,"point_id":"P2","ra":247.75855982169392,"region":"north","slot":"N1","transport_id":"oc3psft_b9e316799740d2d24bc26dd1"},{"band":"z","brick":"2478p325","dec":32.552996950226984,"identity_id":"oc3psf_3114025d69d3bfc634624f47","native_x":2656,"native_y":2528,"point_id":"P2","ra":247.75855982169392,"region":"north","slot":"N1","transport_id":"oc3psft_b9e316799740d2d24bc26dd1"},{"band":"g","brick":"2478p325","dec":32.53665730057891,"identity_id":"oc3psf_055dd631c57b6061958461bd","native_x":384,"native_y":2304,"point_id":"P0","ra":247.9547080790501,"region":"north","slot":"N2","transport_id":"oc3psft_d33d5ee8d4d1aa1538decbf2"},{"band":"r","brick":"2478p325","dec":32.53665730057891,"identity_id":"oc3psf_411dd1511219a63fe6eb8411","native_x":384,"native_y":2304,"point_id":"P0","ra":247.9547080790501,"region":"north","slot":"N2","transport_id":"oc3psft_d33d5ee8d4d1aa1538decbf2"},{"band":"z","brick":"2478p325","dec":32.53665730057891,"identit
